services:
  build:
    image: "ghcr.io/quadtree/emcc:3.1.62"
    stop_signal: SIGKILL
    volumes:
      - ./:/src:ro
      - build:/build
      - output:/output
      - emsdk_cache2:/root/emsdk/upstream/emscripten/cache
      - libs:/tmp/libs
    environment:
      DEBUG_MODE: "${DEBUG_MODE:-1}"
      BUILD_DIR: /build/data
      OUTPUT_DIR: /output/data
      LIBS_DIR: /tmp/libs/data
      TEST_FILE: /tmp/libs/testfile
    command: ["/src/scripts/build.sh"]

  serve:
    image: docker.io/python:3
    stop_signal: SIGKILL
    volumes:
    - ./:/src:ro
    - output:/tmp/output:ro
    ports:
      - 8080:8080
      - 7000:8080
    working_dir: /tmp/output/data
    command: ["python3", "scripts/server.py"]

volumes:
  build:
  output:
  emsdk_cache2:
  libs:
